apiVersion: apps/v1
kind: Deployment
metadata:
  name: vws-backend
  namespace: vws-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%  
  selector:
    matchLabels:
      app: vws-backend
  template:
    metadata:
      labels:
        app: vws-backend
        role: backend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: vwsnode
        image: welasco/nodejsportexhaustion
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"          
        #image: welasco/nodejssockethttpserver
        ports:
        - containerPort: 3001
        readinessProbe:
            httpGet:
               path: /
               port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1        
        livenessProbe:
            httpGet:
                path: /
                port: 3001
                httpHeaders:
                - name: Custom-Header
                  value: Awesome
            initialDelaySeconds: 3
            periodSeconds: 3     
        env:
          - name: PORT
            value: "3001"            